In [25]:
import numpy as np

## DataTypes & Attributes

In [26]:
# NumPy's main datatypes is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [27]:
type(a1)

numpy.ndarray

In [28]:
a2 = np.array([[1, 2, 3.3],
               [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [29]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [30]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [31]:
a1.shape

(3,)

In [32]:
a2.shape

(2, 3)

In [33]:
a3.shape

(2, 3, 3)

In [34]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [35]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [36]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [37]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [38]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [39]:
sample_array  = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [40]:
sample_array.dtype

dtype('int64')

In [41]:
ones = np.ones((2, 3))

In [42]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
ones.dtype

dtype('float64')

In [44]:
type(ones)

numpy.ndarray

In [45]:
zeros = np.zeros((2, 3))

In [46]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [51]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[4, 8, 6, 1, 3],
       [1, 0, 5, 0, 0],
       [6, 5, 6, 0, 9]])

In [52]:
random_array.size

15

In [53]:
random_array.shape

(3, 5)

In [55]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.71706775, 0.26960936, 0.49347864],
       [0.45459239, 0.36431521, 0.60896137],
       [0.00619812, 0.02176245, 0.22061418],
       [0.86725047, 0.38071491, 0.89621373],
       [0.73164663, 0.30006018, 0.26499648]])

In [56]:
random_array_2.shape

(5, 3)

In [57]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.17771842, 0.11819372, 0.5340958 ],
       [0.90092369, 0.61357512, 0.43806795],
       [0.44715257, 0.07957213, 0.38364351],
       [0.61281108, 0.37276948, 0.52149449],
       [0.22113766, 0.81043673, 0.10925075]])